FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY apps/server/release/package.json ./package.json
RUN npm install --omit=dev --no-audit --no-fund
COPY apps/server/release/index.js ./dist/index.js
EXPOSE 5000
CMD ["node", "dist/index.js"]
