import { beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { createApp } from './app.js';
import { MemoryStore } from './store.js';

describe('host is also a player',()=>{
  let store:MemoryStore;let app:ReturnType<typeof createApp>;
  beforeEach(()=>{store=new MemoryStore();app=createApp(store);});
  it('creates one owner member and blocks self review',async()=>{
    const registration=await request(app).post('/api/auth/register').send({account:'host01',password:'password123',displayName:'林导'});
    const token=registration.body.data.token;
    const created=await request(app).post('/api/rooms').set('Authorization',`Bearer ${token}`).send({name:'测试局',ipTheme:'罗小黑战记'});
    expect(created.status).toBe(201);expect(created.body.data.room.members).toHaveLength(1);expect(created.body.data.room.members[0]).toMatchObject({isOwner:true,hostRole:'owner',score:0});expect(created.body.data.room.gamePlan.map((item:{gameId:string})=>item.gameId)).toEqual(['dont','must','truth']);
    const planned=await request(app).post(`/api/rooms/${created.body.data.room.code}/host-actions`).set('Authorization',`Bearer ${token}`).send({action:'set-plan',gamePlan:['draw','story','must']});
    expect(planned.status).toBe(200);expect(planned.body.data.room.gamePlan.map((item:{gameId:string})=>item.gameId)).toEqual(['draw','story','must']);expect(planned.body.data.room.planCursor).toBe(0);
    const review=await request(app).post('/api/reviews/r1/decision').set('Authorization',`Bearer ${token}`).send({ownerAccountId:registration.body.data.user.accountId,roomId:created.body.data.room.id,decision:'approve'});
    expect(review.status).toBe(403);
  });
  it('lets a two-player host start the first planned game',async()=>{
    const host=await request(app).post('/api/auth/register').send({account:'host02',password:'password123',displayName:'主持'});
    const guest=await request(app).post('/api/auth/register').send({account:'guest02',password:'password123',displayName:'玩家'});
    const hostToken=host.body.data.token;const guestToken=guest.body.data.token;
    await request(app).put('/api/profile/me').set('Authorization',`Bearer ${hostToken}`).send({mbti:'ENFP'});
    await request(app).put('/api/profile/me').set('Authorization',`Bearer ${guestToken}`).send({mbti:'ISTJ'});
    const roleBody={ipTheme:'罗小黑战记',name:'无限',personaTags:['沉稳'],quote:'',signatureAction:'',ability:'',isDefault:true};
    const hostRole=await request(app).post('/api/profile/me/roles').set('Authorization',`Bearer ${hostToken}`).send(roleBody);
    const guestRole=await request(app).post('/api/profile/me/roles').set('Authorization',`Bearer ${guestToken}`).send({...roleBody,name:'罗小黑'});
    const created=await request(app).post('/api/rooms').set('Authorization',`Bearer ${hostToken}`).send({name:'两人局',ipTheme:'罗小黑战记'});
    const code=created.body.data.room.code;
    await request(app).post(`/api/rooms/${code}/join`).set('Authorization',`Bearer ${guestToken}`);
    await request(app).put(`/api/rooms/${code}/role`).set('Authorization',`Bearer ${hostToken}`).send({ipRoleId:hostRole.body.data.role.id,ready:true});
    await request(app).put(`/api/rooms/${code}/role`).set('Authorization',`Bearer ${guestToken}`).send({ipRoleId:guestRole.body.data.role.id,ready:true});
    expect([...store.jobs.values()].some(job=>job.kind==='prepare')).toBe(true);
    const started=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'start',gameId:'dont'});
    expect(started.status).toBe(200);expect(started.body.data.room.currentGame).toBe('dont');expect(started.body.data.room.planCursor).toBe(1);expect(started.body.data.room.game.phase).toBe('playing');
    const guestSnapshot=await request(app).get(`/api/rooms/${code}`).set('Authorization',`Bearer ${guestToken}`);
    expect(started.body.data.room.game.privateState.challenge.content).not.toBe(guestSnapshot.body.data.room.game.privateState.challenge.content);
    expect(started.body.data.room.game.privateState.dont.wordCount).toBe(1);
    expect(guestSnapshot.body.data.room.game.privateState.dont.wordCount).toBe(1);
    const guestWord=guestSnapshot.body.data.room.game.privateState.challenge.content;
    const changed=await request(app).post(`/api/rooms/${code}/actions`).set('Authorization',`Bearer ${hostToken}`).send({actionId:'change-word-0001',gameId:'dont',action:'change-challenge'});
    expect(changed.status).toBe(200);expect(changed.body.data.room.game.privateState.challenge.content).not.toBe(started.body.data.room.game.privateState.challenge.content);expect(changed.body.data.room.game.privateState.dont.wordCount).toBe(2);
    const unchangedGuest=await request(app).get(`/api/rooms/${code}`).set('Authorization',`Bearer ${guestToken}`);
    expect(unchangedGuest.body.data.room.game.privateState.challenge.content).toBe(guestWord);expect(unchangedGuest.body.data.room.game.privateState.dont.wordCount).toBe(1);
    const hostOverview=await request(app).get(`/api/rooms/${code}/overview`).set('Authorization',`Bearer ${hostToken}`);
    const guestOverview=await request(app).get(`/api/rooms/${code}/overview`).set('Authorization',`Bearer ${guestToken}`);
    expect(hostOverview.body.data.overview.players.every((player:{currentWord:string})=>Boolean(player.currentWord))).toBe(true);
    expect(guestOverview.body.data.overview.players.find((player:{accountId:string})=>player.accountId===guest.body.data.user.accountId)).toMatchObject({currentWord:null,currentWordHidden:true});
    expect(guestOverview.body.data.overview.players.find((player:{accountId:string})=>player.accountId===host.body.data.user.accountId).currentWord).toBeTruthy();
    const noReason=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'set-player-word',targetAccountId:host.body.data.user.accountId,content:'点头'});
    expect(noReason.status).toBe(400);
    const edited=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'set-player-word',targetAccountId:host.body.data.user.accountId,content:'点头',reason:'适配现场条件'});
    expect(edited.status).toBe(200);expect(edited.body.data.room.game.privateState.challenge.content).toBe('点头');expect(edited.body.data.room.game.privateState.dont.wordCount).toBe(3);
    const settled=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'settle'});
    expect(settled.body.data.room.game.publicState.winnerAccountIds).toEqual([guest.body.data.user.accountId]);
    const timeline=await request(app).get(`/api/rooms/${code}/timeline`).set('Authorization',`Bearer ${guestToken}`);
    expect(timeline.status).toBe(200);expect(timeline.body.data.timeline.items[0]).toMatchObject({gameId:'dont',status:'completed',sessionId:started.body.data.room.game.sessionId});
    const history=await request(app).get(`/api/rooms/${code}/sessions/${started.body.data.room.game.sessionId}/history`).set('Authorization',`Bearer ${guestToken}`);
    expect(history.status).toBe(200);expect(history.body.data.history.dont.players).toHaveLength(2);const hostHistory=history.body.data.history.dont.players.find((item:{accountId:string})=>item.accountId===host.body.data.user.accountId);expect(hostHistory.words).toContain('点头');expect(hostHistory.currentWord).toBe('点头');expect(hostHistory.usedWords).not.toContain('点头');
    const immutable=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'set-plan',gamePlan:settled.body.data.room.gamePlan.slice(1)});
    expect(immutable.status).toBe(409);
    const outsider=await request(app).post('/api/auth/register').send({account:'outsider02',password:'password123',displayName:'路人'});
    const forbidden=await request(app).get(`/api/rooms/${code}/sessions/${started.body.data.room.game.sessionId}/history`).set('Authorization',`Bearer ${outsider.body.data.token}`);
    expect(forbidden.status).toBe(403);
    const recent=await request(app).get('/api/rooms/recent?limit=3').set('Authorization',`Bearer ${guestToken}`);
    expect(recent.body.data.rooms[0]).toMatchObject({code,canReenter:true,currentGame:'dont'});
    const rejoined=await request(app).post(`/api/rooms/${code}/rejoin`).set('Authorization',`Bearer ${guestToken}`);
    expect(rejoined.status).toBe(200);expect(rejoined.body.data.room.members.find((item:{accountId:string})=>item.accountId===guest.body.data.user.accountId).playerRole).toBe('罗小黑');
    const guestCannotAdvance=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${guestToken}`).send({action:'start-next'});
    expect(guestCannotAdvance.status).toBe(403);
    const nextStarted=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'start-next'});
    expect(nextStarted.status).toBe(200);expect(nextStarted.body.data.room.currentGame).toBe('must');expect(nextStarted.body.data.room.planCursor).toBe(2);
    const guestMust=await request(app).get(`/api/rooms/${code}`).set('Authorization',`Bearer ${guestToken}`);const hostMission=nextStarted.body.data.room.game.privateState.challenge.content;const guestMission=guestMust.body.data.room.game.privateState.challenge.content;
    expect(hostMission).toMatch(/^当看到有人.+，你必须立刻.+$/);expect(guestMission).toMatch(/^当看到有人.+，你必须立刻.+$/);expect(hostMission).not.toBe(guestMission);expect(JSON.stringify(nextStarted.body.data.room.game.publicState)).not.toContain(hostMission);expect(JSON.stringify(guestMust.body.data.room.game.privateState)).not.toContain(hostMission);
    const currentPools=await store.listGeneratedContent(`content-pool:v1:${created.body.data.room.id}:must`);expect(currentPools).toHaveLength(2);expect([...store.jobs.values()].some(job=>job.kind==='pool')).toBe(true);expect(JSON.stringify(nextStarted.body.data.room)).not.toContain('fingerprint');
    const triggered=await request(app).post(`/api/rooms/${code}/actions`).set('Authorization',`Bearer ${hostToken}`).send({actionId:'must-trigger-0001',gameId:'must',action:'must-triggered'});expect(triggered.body.data.room.game.privateState.must).toEqual({triggerCount:1,cardChangeCount:0});expect(triggered.body.data.room.game.phase).toBe('playing');
    const forced=await request(app).post(`/api/rooms/${code}/actions`).set('Authorization',`Bearer ${hostToken}`).send({actionId:'must-change-0001',gameId:'must',action:'must-forced-change'});expect(forced.body.data.room.game.privateState.must).toEqual({triggerCount:1,cardChangeCount:1});expect(forced.body.data.room.game.privateState.challenge.content).not.toBe(hostMission);
    const mustSessionId=nextStarted.body.data.room.game.sessionId;const replayed=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'replay-game',sourceSessionId:started.body.data.room.game.sessionId});
    expect(replayed.status).toBe(200);expect(replayed.body.data.room.currentGame).toBe('dont');expect(replayed.body.data.room.game.sessionId).not.toBe(started.body.data.room.game.sessionId);expect(replayed.body.data.room.gamePlan.map((item:{gameId:string})=>item.gameId)).toEqual(['dont','must','dont','truth']);expect(replayed.body.data.room.planCursor).toBe(3);
    expect((await store.getGameSessionRecord(mustSessionId))?.endedAt).toBeTruthy();expect((await store.getGameSessionRecord(started.body.data.room.game.sessionId))?.endedAt).toBeTruthy();
    const closed=await request(app).post(`/api/rooms/${code}/host-actions`).set('Authorization',`Bearer ${hostToken}`).send({action:'close-room',reason:'本次聚会已经结束'});
    expect(closed.status).toBe(200);expect(closed.body.data.room.closedAt).toBeTruthy();
    const blocked=await request(app).post(`/api/rooms/${code}/rejoin`).set('Authorization',`Bearer ${guestToken}`);
    expect(blocked.status).toBe(400);
  });
  it('uses the tab bearer token before a shared cookie',async()=>{
    const first=await request(app).post('/api/auth/register').send({account:'first03',password:'password123',displayName:'甲'});
    const second=await request(app).post('/api/auth/register').send({account:'second03',password:'password123',displayName:'乙'});
    const sharedCookie=first.headers['set-cookie'];
    const profile=await request(app).get('/api/profile/me').set('Cookie',sharedCookie).set('Authorization',`Bearer ${second.body.data.token}`);
    expect(profile.status).toBe(200);expect(profile.body.data.profile.displayName).toBe('乙');
  });
  it('keeps completed history outside the twelve-game upcoming limit',async()=>{
    const registration=await request(app).post('/api/auth/register').send({account:'planner04',password:'password123',displayName:'编排者'});const token=registration.body.data.token;
    const created=await request(app).post('/api/rooms').set('Authorization',`Bearer ${token}`).send({name:'长聚会',ipTheme:'罗小黑战记'});const room=created.body.data.room;
    room.gamePlan=Array.from({length:12},(_,index)=>({id:`locked-${index}`,gameId:index%2?'must':'dont',createdAt:new Date().toISOString()}));room.planCursor=12;await store.saveRoom(room);
    const extended=await request(app).post(`/api/rooms/${room.code}/host-actions`).set('Authorization',`Bearer ${token}`).send({action:'set-plan',gamePlan:[...room.gamePlan,'story']});
    expect(extended.status).toBe(200);expect(extended.body.data.room.gamePlan).toHaveLength(13);expect(extended.body.data.room.planCursor).toBe(12);expect(extended.body.data.room.gamePlan[12].gameId).toBe('story');
    const tooMany=await request(app).post(`/api/rooms/${room.code}/host-actions`).set('Authorization',`Bearer ${token}`).send({action:'set-plan',gamePlan:[...room.gamePlan,...Array.from({length:13},()=> 'draw')]});
    expect(tooMany.status).toBe(400);expect(tooMany.body.error).toContain('后续编排最多保留 12 场');
  });
});
