(some characters truncated)...
?'';const guess=String(input.payload?.guess||'').trim();
        const correct=matchesDraw({word,aliases:draw?.aliases??[],difficulty:'easy'},guess);input.payload={...(input.payload as Record<string,unknown>),correct};handleGameAction(room,req.auth!.accountId,input);
      }else handleGameAction(room,req.auth!.accountId,input);
      if(asset)await store.saveAsset({...asset,usedInSessionId:room.game!.sessionId,usedAt:new Date().toISOString()});
      await persistRoom(store,room);
      if(room.game)await store.addGameEvent(room.game.sessionId,req.auth!.accountId,input.action,['witch','dont','must','truth','story','shopping','undercover'].includes(input.gameId)?'public_after_settle':'public',input.payload??{});
      return room;
    });
    if(!duplicate)broadcastRoom(room);res.json({ok:true,data:{...(duplicate?{duplicate:true}:{}),room:playerSnapshot(room,req.auth!.accountId)}});
  }catch(error){next(error);}});
  app.post('/api/rooms/:code/host-actions',async(req,res,next)=>{try{
    const result=await store.atomic(async store=>{
    const room=await roomForMember(store,req.params.code,req.auth!.accountId);ensureOpen(room);const actor=room.members.find(item=>item.accountId===req.auth!.accountId)!;
    const beforeAuction=room.currentGame==='auction'?structuredClone(room.game?.publicState.currentLot):null;
    if(!actor.hostRole)return {status:403,body:{ok:false,error:'没有主持权限'}};const action=String(req.body.action||'');
    const rawOptions=req.body.options as {rounds?:unknown;boardSize?:unknown}|undefined;const options:{rounds?:number;boardSize?:number}|undefined=rawOptions?{rounds:Number.isInteger(Number(rawOptions.rounds))?Number(rawOptions.rounds):undefined,boardSize:Number.isInteger(Number(rawOptions.boardSize))?Number(rawOptions.boardSize):undefined}:undefined;
    if(action==='set-plan'){
      const requested=normalizeRequestedPlan(req.body.gamePlan);const locked=room.gamePlan.slice(0,room.planCursor);const upcomingCount=requested.length-locked.length;if(upcomingCount<0||upcomingCount>12)return {status:400,body:{ok:false,error:'后续编排最多保留 12 场尚未开始的游戏'}};if(requested.length===0)return {status:400,body:{ok:false,error:'聚会编排至少需要保留一场游戏或历史经历'}};if(locked.some((item,index)=>requested[index]?.id!==item.id||requested[index]?.gameId!==item.gameId))return {status:409,body:{ok:false,error:'已开始或已完成的游戏经历不能删除、改序或覆盖'}};if(new Set(requested.map(item=>item.id)).size!==requested.length)return {status:400,body:{ok:false,error:'编排项标识不能重复'}};room.gamePlan=requested;
    }else if(action==='start'){
      if(room.game&&room.game.phase!=='settled')await settleBeforeStarting(store,room,actor.accountId,'主持跳过当前游戏');const requestedId=String(req.body.gameId||'') as GameId;if(!GAME_IDS.includes(requestedId))throw new Error('请先编排至少一场游戏');const planIdx=room.gamePlan.findIndex(p=>p.gameId===requestedId);if(planIdx<0)throw new Error('该游戏不在当前编排中');const targetPlan=room.gamePlan[planIdx];await prepareAndStartGame(store,room,requestedId,targetPlan.id,options);room.planCursor=Math.max(room.planCursor,planIdx+1);room.planRound=1;
    }else if(action==='start-next'){
      await settleBeforeStarting(store,room,actor.accountId,'提前开始下一场');const planned=room.gamePlan[room.planCursor];if(!planned)throw new Error('聚会编排中没有下一场游戏');await prepareAndStartGame(store,room,planned.gameId,planned.id,options);const total=planned.rounds??1;if(room.planRound<total)room.planRound++;else{room.planRound=1;room.planCursor=Math.min(room.planCursor+1,room.gamePlan.length);}
    }else if(action==='replay-game'){
      if(room.gamePlan.length-room.planCursor>=12)throw new Error('后续编排最多保留 12 场，请先调整尚未开始的项目');const sourceSessionId=String(req.body.sourceSessionId||'');const source=await store.getGameSessionRecord(sourceSessionId);const sourceGame=source?.state as {game?:GameSnapshot}|undefined;if(!source||source.roomId!==room.id||(source.endedAt===null&&sourceGame?.game?.phase!=='settled'))throw new Error('只能重玩本房间已经完成的游戏');await settleBeforeStarting(store,room,actor.accountId,'重玩历史游戏');const replayItem=createPlanItem(source.gameId);room.gamePlan.splice(room.planCursor,0,replayItem);room.planRound=1;await prepareAndStartGame(store,room,source.gameId,replayItem.id,options);room.planCursor=Math.min(room.planCursor+1,room.gamePlan.length);
    }else if(action==='pause')room.status='paused';
    else if(action==='resume')room.status='running';
    else if(action==='add-time'){if(room.game?.endsAt)room.game.endsAt+=300_000;}
    else if(action==='settle'){if(room.currentGame==='undercover'&&undercoverState(room)?.stage!=='complete')abortUndercover(room);settleGame(room);}
    else if(action==='restart-draw'){if(room.currentGame!=='draw'||!room.game)throw new Error('当前不是你画我猜');restartDrawGame(room);const item=await takePoolItem(store,room,'draw');Object.assign(room.game.privateState!.draw as object,item.value);await store.addAudit(room.id,actor.accountId,'restart-draw','重新开始你画我猜',{});}
    else if(action==='advance-stage'){const reason=requiredReason(req.body.reason);const before=room.game?{phase:room.game.phase,round:room.game.round}:null;if(room.currentGame==='story'){const story=storyState(room)!;if(req.body.expectedStage!==story.stage||(story.stage==='relay'&&req.body.expectedSpeakerId!==story.order[story.currentSpeakerIndex]))throw new Error('进程已更新，请刷新后重试');}advanceGameStage(room);await store.addAudit(room.id,actor.accountId,'advance-stage',reason,{before,after:room.game?{phase:room.game.phase,round:room.game.round}:null});}
    else if(action==='replace-player-word'||action==='set-player-word'||action==='adjust-word-count'){
      if(room.currentGame!=='dont'||!room.game)throw new Error('当前不是不要做挑战');const reason=requiredReason(req.body.reason);const targetAccountId=String(req.body.targetAccountId||'');const target=room.members.find(item=>item.accountId===targetAccountId&&item.ready);if(!target)throw new Error('没有找到该玩家');const before=gameOverview(room,actor.accountId)?.players.find(item=>item.accountId===targetAccountId);
      if(action==='replace-player-word'){const profile=await store.getProfile(targetAccountId);const role=profile.roles.find(item=>item.id===target.ipRoleId);if(!profile.mbti||!role)throw new Error('该玩家尚未设置 MBTI 或角色');const challenge=(await takePoolItem(store,room,'dont',targetAccountId)).value as Challenge;replacePlayerChallenge(room,targetAccountId,challenge);}
      if(action==='set-player-word')setPlayerChallenge(room,targetAccountId,String(req.body.content||''));
      if(action==='adjust-word-count')setDontWordCount(room,targetAccountId,Number(req.body.wordCount));
      const after=gameOverview(room,actor.accountId)?.players.find(item=>item.accountId===targetAccountId);await store.addAudit(room.id,actor.accountId,action,reason,{targetAccountId,before,after});
    }else if(action==='close-room'){const reason=requiredReason(req.body.reason);room.closedAt=new Date().toISOString();room.status='stopped';await store.addAudit(room.id,actor.accountId,'close-room',reason);}
    else if(action==='emergency'){const reason=requiredReason(req.body.reason);room.status='stopped';await store.addAudit(room.id,actor.accountId,'emergency-stop',reason);}
    else if(action==='audit-view'){const reason=requiredReason(req.body.reason);await store.addAudit(room.id,actor.accountId,'private-audit',reason,{targetAccountId:req.body.targetAccountId});}
    else if(action==='remove-member'){const targetAccountId=String(req.body.targetAccountId||'');if(targetAccountId===actor.accountId)throw new Error('不能踢出自己');const target=room.members.find(item=>item.accountId===targetAccountId);if(!target)throw new Error('没有找到该成员');broadcast(room.code,{type:'room:kicked',roomCode:room.code},targetAccountId);room.members=room.members.filter(item=>item.accountId!==targetAccountId);if(room.game){const gs=room.game.privateState;if(gs){if(gs.order&&Array.isArray(gs.order))gs.order=(gs.order as string[]).filter(id=>id!==targetAccountId);if(gs.drawings&&Array.isArray(gs.drawings)&&gs.currentIndex!=null){gs.drawings=(gs.drawings as string[]).filter((_,i)=>i<=(gs.currentIndex as number));}if(gs.truth&&typeof gs.truth==='object'){(gs.truth as Record<string,unknown>).submissions=Object.fromEntries(Object.entries((gs.truth as {submissions?:Record<string,unknown>}).submissions??{}).filter(([k])=>k!==targetAccountId));}}}await store.addAudit(room.id,actor.accountId,'remove-member','踢出成员',{targetAccountId,displayName:target.displayName});}
    else if(action==='set-team'){const targetAccountId=String(req.body.targetAccountId||'');const team=String(req.body.team||'未分队').slice(0,30);const target=room.members.find(item=>item.accountId===targetAccountId);if(!target)throw new Error('没有找到该成员');target.team=team;await store.addAudit(room.id,actor.accountId,'set-team','调整队伍',{targetAccountId,displayName:target.displayName,team});}
    else if(action==='rename-team'){const oldName=String(req.body.oldName||'');const newName=String(req.body.newName||'').trim().slice(0,30);if(!oldName)throw new Error('原队名不能为空');if(!newName)throw new Error('新队名不能为空');if(newName==='未分队')throw new Error('"未分队"是保留名');if(oldName===newName)throw new Error('新旧队名相同');const affected=room.members.filter(m=>m.team===oldName);if(!affected.length)throw new Error('没有找到该队伍');affected.forEach(m=>m.team=newName);await store.addAudit(room.id,actor.accountId,'rename-team','重命名队伍',{oldName,newName,memberCount:affected.length});}
    else if(action==='delete-team'){const teamName=String(req.body.team||'');if(!teamName)throw new Error('队名不能为空');if(teamName==='未分队')throw new Error('不能删除保留队伍');const affected=room.members.filter(m=>m.team===teamName);affected.forEach(m=>m.team='未分队');await store.addAudit(room.id,actor.accountId,'delete-team','解散队伍',{team:teamName,memberCount:affected.length});}
    else if(action==='transfer-owner'){if(!actor.isOwner)throw new Error('只有房主可以转让');const targetAccountId=String(req.body.targetAccountId||'');if(targetAccountId===actor.accountId)throw new Error('不能转让给自己');const target=room.members.find(item=>item.accountId===targetAccountId);if(!target)throw new Error('没有找到该成员');actor.isOwner=false;actor.hostRole=null;target.isOwner=true;target.hostRole='owner';await store.addAudit(room.id,actor.accountId,'transfer-owner','转让房主',{targetAccountId,displayName:target.displayName});}
    else throw new Error('未知主持操作');
    await persistRoom(store,room,action==='settle'||action==='close-room');if(action==='advance-stage'&&beforeAuction&&room.game){const lot=(room.game.privateState?.auction as {lots:Array<{lotId:string;soldAt:number|null}>}).lots.find(l=>l.lotId===(beforeAuction as {lotId:string}).lotId);if(lot?.soldAt)await store.addGameEvent(room.game.sessionId,actor.accountId,'auction-sold','public',{...lot});}if(room.game){const visibility=action==='replace-player-word'||action==='set-player-word'||action==='adjust-word-count'?'public_after_settle':'public';await store.addGameEvent(room.game.sessionId,actor.accountId,action,visibility,eventPayload(action,req.body));}return {status:200,body:{ok:true,data:{room:playerSnapshot(room,req.auth!.accountId)}},room};
    });if(result.room)broadcastRoom(result.room);res.status(result.status).json(result.body);
  }catch(error){next(error);}});

  app.post('/api/reviews/:id/decision',async(req,res,next)=>{try{const ownerAccountId=String(req.body.ownerAccountId||'');if(ownerAccountId===req.auth!.accountId)return res.status(403).json({ok:false,error:'不能审核自己的提交'});await store.addAudit(String(req.body.roomId||''),req.auth!.accountId,'review-decision',String(req.body.reason||'审核处理'),{reviewId:req.params.id,decision:req.body.decision,ownerAccountId});res.json({ok:true});}catch(error){next(error);}});
  app.post('/api/content/generate',async(req,res,next)=>{try{const profile=await store.getProfile(req.auth!.accountId);const role=profile.roles.find(item=>item.id===req.body.ipRoleId);if(!profile.mbti||!role)return res.status(400).json({ok:false,error:'请先设置 MBTI 和角色'});const result=await generateContent({gameId:req.body.gameId,mbti:profile.mbti,role,playerCount:Math.max(2,Number(req.body.playerCount)||2),seenIds:req.body.seenIds,cameraAvailable:Boolean(req.body.cameraAvailable)});res.json({ok:true,data:result});}catch(error){next(error);}});

  app.get('/api/games',(_req,res)=>res.json({ok:true,data:{games:Object.values(GAME_DEFINITIONS)}}));
  app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{const message=error instanceof Error?error.message:'请求处理失败';res.status(400).json({ok:false,error:message});});
  return app;
}

function setSession(res:express.Response,token:string){res.cookie('rxj_session',token,{httpOnly:true,sameSite:'lax',secure:config.cookieSecure,maxAge:7*24*60*60*1000});}
async function loadRoom(store:Store,codeInput:string){const code=roomCodeSchema.parse(codeInput.toUpperCase());const found=await store.getRoom(code);if(!found)return null;const room=normalizeRoom(found);if(room.game?.sessionId){const saved=await store.getGameSession(room.game.sessionId) as {game?:GameSnapshot;runtime?:PersistedRuntime}|null;if(saved?.game)room.game=saved.game;if(saved?.runtime)restoreRuntime(room,saved.runtime);ensureStoryGame(room);ensureShoppingGame(room);ensureUndercover(room);}return room;}
async function roomForMember(store:Store,codeInput:string,accountId:string){const room=await loadRoom(store,codeInput);if(!room)throw new Error('没有找到这个房间');if(!room.members.some(member=>member.accountId===accountId))throw new Error('请先加入房间');return room;}
function normalizeRoom(room:RoomSnapshot){const raw=(Array.isArray(room.gamePlan)&&room.gamePlan.length?room.gamePlan:planFor(30,4)) as unknown[];room.gamePlan=raw.map((value,index)=>{if(typeof value==='string')return {id:`legacy-${room.id}-${index}-${value}`,gameId:value as GameId,createdAt:'1970-01-01T00:00:00.000Z',rounds:1};const item=value as GamePlanItem;const rawRounds=Number(item.rounds);const rounds=Number.isInteger(rawRounds)&&rawRounds>=1&&rawRounds<=99?rawRounds:1;return {...item,rounds};}).filter(item=>GAME_IDS.includes(item.gameId));room.planCursor=Number.isInteger(room.planCursor)?Math.max(0,Math.min(room.planCursor,room.gamePlan.length)):0;room.planRound=Number.isInteger(room.planRound)?Math.max(1,room.planRound):1;room.closedAt=room.closedAt??null;if(room.game&&!room.game.sessionId)room.game.sessionId=randomUUID();if(room.game&&room.game.planItemId===undefined)room.game.planItemId=room.gamePlan[Math.max(0,room.planCursor-1)]?.id??null;ensureWitchGame(room);ensureAuctionGame(room);ensureStoryGame(room);ensureShoppingGame(room);ensureUndercover(room);return ensureTruthGame(room);}
async function persistRoom(store:Store,room:RoomSnapshot,ended=false){await store.saveRoom(room);if(room.game)await store.saveGameSession(room,{game:room.game,runtime:serializeRuntime(room)},ended);}
async function settleBeforeStarting(store:Store,room:RoomSnapshot,actorAccountId:string,reason:string){if(!room.game||room.game.phase==='settled')return;const sessionId=room.game.sessionId;settleGame(room);await persistRoom(store,room,true);await store.addGameEvent(sessionId,actorAccountId,'settle','public',{reason});}
async function prepareAndStartGame(store:Store,room:RoomSnapshot,gameId:GameId,planItemId:string|null,options?:{rounds?:number;boardSize?:number}){const profiles=new Map<string,{mbti:Mbti;role:IpRole}>();for(const member of room.members.filter(item=>item.ready)){const profile=await store.getProfile(member.accountId);const role=profile.roles.find(item=>item.id===member.ipRoleId);if(profile.mbti&&role)profiles.set(member.accountId,{mbti:profile.mbti,role});}const challengeInputs=[...profiles].map(([accountId,profile])=>({accountId,context:{gameId,mbti:profile.mbti,role:profile.role,playerCount:profiles.size,cameraAvailable:false}}));let challenges=new Map<string,Challenge>();if(gameId==='dont'||gameId==='must'){for(const {accountId} of challengeInputs){const active=[...challenges.values()].map(c=>c.content);const item=await takePoolItem(store,room,gameId,accountId,active);challenges.set(accountId,item.value as Challenge);}}else if(!['truth','auction','story','shopping','draw'].includes(gameId)){challenges=new Map(await Promise.all(challengeInputs.map(async({accountId,context})=>{const result=await generateContent(context);return [accountId,result.challenge] as const;})));}let shoppingWallets:Record<string,number>|null=null;if(gameId==='shopping'){const sessions=await store.listGameSessions(room.id);const auction=[...sessions].reverse().find(session=>session.gameId==='auction'&&Boolean(session.endedAt));const saved=auction?.state as {game?:{privateState?:{auction?:{wallets?:Record<string,number>}}}}|undefined;shoppingWallets=saved?.game?.privateState?.auction?.wallets??null;}startGame(room,gameId,profiles,challenges,planItemId,shoppingWallets,options);if(gameId==='story'){const item=await takePoolItem(store,room,'story');applyStoryBundle(room,item.value as StoryBundle,item.source);}if(gameId==='draw'){const item=await takePoolItem(store,room,'draw');Object.assign(room.game!.privateState!.draw as object,item.value);}}
function currentMustContents(room:RoomSnapshot,excludeAccountId?:string){return room.members.filter(member=>member.ready&&member.accountId!==excludeAccountId).map(member=>(playerSnapshot(room,member.accountId).game?.privateState?.challenge as {content?:string}|undefined)?.content).filter((content):content is string=>Boolean(content));}
function broadcastRoom(room:RoomSnapshot){broadcast(room.code,{type:'room:state',room:publicRoom(room)});for(const member of room.members)broadcast(room.code,{type:'game:private-state',room:playerSnapshot(room,member.accountId)},member.accountId);}
function requiredReason(value:unknown){const reason=String(value||'').trim();if(reason.length<4)throw new Error('请填写至少 4 个字的修改原因');return reason.slice(0,255);}
function ensureOpen(room:RoomSnapshot){if(room.closedAt)throw new Error('这场聚会已经结束，不能继续操作');}
function publicRoom(room:RoomSnapshot){const copy=structuredClone(room);if(copy.game)delete copy.game.privateState;return copy;}
function normalizeRequestedPlan(value:unknown):GamePlanItem[]{if(!Array.isArray(value))return [];const items=value.map(item=>{if(typeof item==='string'&&GAME_IDS.includes(item as GameId))return createPlanItem(item as GameId);if(item&&typeof item==='object'){const candidate=item as Partial<GamePlanItem>;if(typeof candidate.id==='string'&&candidate.id&&candidate.gameId&&GAME_IDS.includes(candidate.gameId)){const rawRounds=Number(candidate.rounds);const rounds=Number.isInteger(rawRounds)&&rawRounds>=1&&rawRounds<=99?rawRounds:1;return {id:candidate.id.slice(0,80),gameId:candidate.gameId,createdAt:typeof candidate.createdAt==='string'?candidate.createdAt:new Date().toISOString(),rounds};}}return null;});return items.some(item=>!item)?[]:items as GamePlanItem[];}
function eventPayload(action:string,body:Record<string,unknown>){if(action==='set-player-word')return {action,targetAccountId:body.targetAccountId,content:body.content};if(action==='replace-player-word'||action==='adjust-word-count')return {action,targetAccountId:body.targetAccountId,wordCount:body.wordCount};if(action==='replay-game')return {action,sourceSessionId:body.sourceSessionId};return {action};}

