import { describe,expect,it } from 'vitest';
import { isDistinctSecretMission,type ChallengeContext,type IpRole } from '@ruxiju/shared';
import { MemoryStore } from './store.js';
import { prewarmMustPool,refillMustPool,takeMustChallenge,type SecretMissionPool } from './secret-mission-pool.js';

const role:IpRole={id:'role-1',ipTheme:'罗小黑战记',name:'罗小黑',personaTags:['活泼','热情'],quote:'我想回家',signatureAction:'挥手',ability:'空间系能力',isDefault:true};
const context:ChallengeContext={gameId:'must',mbti:'ENFP',role,playerCount:3,cameraAvailable:false};

describe('secret mission pool',()=>{
  it('prewarms ten personalized, unique and persistent cards',async()=>{const store=new MemoryStore();const first=await prewarmMustPool(store,'room-1','account-1',context);expect(first.items).toHaveLength(10);expect(new Set(first.items.map(item=>item.challenge.content)).size).toBe(10);expect(first.items.filter(item=>item.challenge.title==='基础隐蔽款')).toHaveLength(2);expect(first.items.filter(item=>item.challenge.title==='MBTI 触发款')).toHaveLength(4);expect(first.items.filter(item=>item.challenge.title==='网络梗整活款')).toHaveLength(4);const again=await prewarmMustPool(store,'room-1','account-1',context);expect(again.items.map(item=>item.id)).toEqual(first.items.map(item=>item.id));});
  it('keeps room pools unique and active cards strongly distinct',async()=>{const store=new MemoryStore();const one=await prewarmMustPool(store,'room-2','account-1',context);const two=await prewarmMustPool(store,'room-2','account-2',{...context,role:{...role,id:'role-2',name:'无限',personaTags:['沉稳','冷静']},mbti:'INTJ'});expect(new Set([...one.items,...two.items].map(item=>item.challenge.content)).size).toBe(20);const first=await takeMustChallenge(store,'room-2','account-1',context);const second=await takeMustChallenge(store,'room-2','account-2',{...context,role:{...role,id:'role-2',name:'无限',personaTags:['沉稳','冷静']},mbti:'INTJ'},[first.content]);expect(isDistinctSecretMission(second.content,[first.content])).toBe(true);});
  it('replaces an outdated profile pool without forgetting retired content',async()=>{const store=new MemoryStore();const old=await prewarmMustPool(store,'room-3','account-1',context);const changed=await prewarmMustPool(store,'room-3','account-1',{...context,mbti:'INFP'});expect(changed.profileFingerprint).not.toBe(old.profileFingerprint);expect(changed.retiredContents).toEqual(expect.arrayContaining(old.items.map(item=>item.challenge.content)));expect(changed.items).toHaveLength(10);const saved=await store.getGeneratedContent('must-pool:v2:room-3:account-1');expect((saved?.content as SecretMissionPool).items).toHaveLength(10);});
  it('adds ten more cards when only two remain',async()=>{const store=new MemoryStore();await prewarmMustPool(store,'room-4','account-1',context);for(let index=0;index<8;index++)await takeMustChallenge(store,'room-4','account-1',context);await refillMustPool(store,'room-4','account-1',context);const saved=await store.getGeneratedContent('must-pool:v2:room-4:account-1');const pool=saved?.content as SecretMissionPool;expect(pool.items).toHaveLength(20);expect(pool.items.filter(item=>!item.usedAt)).toHaveLength(12);expect(new Set(pool.items.map(item=>item.challenge.content)).size).toBe(20);});
});
