import { createHash, randomUUID } from 'node:crypto';
import { buildSecretMissionBatch, isDistinctSecretMission, parseSecretMission, validateChallenge, type Challenge, type ChallengeContext } from '@ruxiju/shared';
import { cacheGet, cacheSet } from './cache.js';
import { generateMustChallengeBatch } from './content-service.js';
import type { Store } from './store.js';

const RULES_VERSION=7;const CACHE_TTL=21_600;const locks=new Map<string,Promise<unknown>>();
export interface SecretMissionPoolItem {id:string;challenge:Challenge;trigger:string;action:string;source:'local'|'ai';createdAt:string;usedAt:string|null}
export interface SecretMissionPool {roomId:string;accountId:string;profileFingerprint:string;rulesVersion:number;items:SecretMissionPoolItem[];retiredContents:string[];updatedAt:string}

function poolKey(roomId:string,accountId:string){return `must-pool:v2:${roomId}:${accountId}`;}
function poolPrefix(roomId:string){return `must-pool:v2:${roomId}:`;}
function fingerprint(context:ChallengeContext){return createHash('sha256').update(JSON.stringify({mbti:context.mbti,role:context.role,gameId:'must'})).digest('hex');}
function validPool(value:unknown):value is SecretMissionPool{return Boolean(value&&typeof value==='object'&&Array.isArray((value as SecretMissionPool).items));}
async function locked<T>(roomId:string,task:()=>Promise<T>):Promise<T>{const previous=locks.get(roomId)??Promise.resolve();const current=previous.catch(()=>undefined).then(task);locks.set(roomId,current);try{return await current;}finally{if(locks.get(roomId)===current)locks.delete(roomId);}}
async function loadPool(store:Store,roomId:string,accountId:string){const key=poolKey(roomId,accountId);const cached=await cacheGet<SecretMissionPool>(key);if(validPool(cached))return cached;const record=await store.getGeneratedContent(key);if(validPool(record?.content)){await cacheSet(key,record.content,CACHE_TTL);return record.content;}return null;}
async function savePool(store:Store,pool:SecretMissionPool){const key=poolKey(pool.roomId,pool.accountId);pool.updatedAt=new Date().toISOString();await store.saveGeneratedContent({cacheKey:key,accountId:pool.accountId,gameId:'must',content:pool,rulesVersion:RULES_VERSION});await cacheSet(key,pool,CACHE_TTL);}
function itemFor(challenge:Challenge,source:'local'|'ai'):SecretMissionPoolItem|null{const parts=parseSecretMission(challenge.content);if(!parts||!validateChallenge(challenge))return null;return {id:randomUUID(),challenge,trigger:parts.trigger,action:parts.action,source,createdAt:new Date().toISOString(),usedAt:null};}
async function roomContents(store:Store,roomId:string){const records=await store.listGeneratedContent(poolPrefix(roomId));return records.flatMap(record=>validPool(record.content)?[...(record.content.retiredContents??[]),...record.content.items.map(item=>item.challenge.content)]:[]);}
async function appendBatch(store:Store,pool:SecretMissionPool,context:ChallengeContext,useAi:boolean){const excluded=await roomContents(store,pool.roomId);const generated=useAi?await generateMustChallengeBatch({...context,gameId:'must'},10,excluded):buildSecretMissionBatch({...context,gameId:'must'},10,excluded).map(challenge=>({source:'local' as const,challenge}));for(const value of generated){const item=itemFor(value.challenge,value.source);if(item&&!excluded.includes(item.challenge.content)){pool.items.push(item);excluded.push(item.challenge.content);}}await savePool(store,pool);}

export async function prewarmMustPool(store:Store,roomId:string,accountId:string,context:ChallengeContext){return locked(roomId,async()=>{const expected=fingerprint(context);let pool=await loadPool(store,roomId,accountId);if(!pool||pool.rulesVersion!==RULES_VERSION||pool.profileFingerprint!==expected){const retired=pool?[...(pool.retiredContents??[]),...pool.items.map(item=>item.challenge.content)]:[];pool={roomId,accountId,profileFingerprint:expected,rulesVersion:RULES_VERSION,items:[],retiredContents:retired,updatedAt:new Date().toISOString()};}if(!pool.items.some(item=>!item.usedAt))await appendBatch(store,pool,context,true);return pool;});}

export async function takeMustChallenge(store:Store,roomId:string,accountId:string,context:ChallengeContext,activeContents:string[]=[]){const result=await locked(roomId,async()=>{const expected=fingerprint(context);let pool=await loadPool(store,roomId,accountId);if(!pool||pool.rulesVersion!==RULES_VERSION||pool.profileFingerprint!==expected){const retired=pool?[...(pool.retiredContents??[]),...pool.items.map(item=>item.challenge.content)]:[];pool={roomId,accountId,profileFingerprint:expected,rulesVersion:RULES_VERSION,items:[],retiredContents:retired,updatedAt:new Date().toISOString()};}if(!pool.items.some(item=>!item.usedAt))await appendBatch(store,pool,context,false);let item=pool.items.find(candidate=>!candidate.usedAt&&isDistinctSecretMission(candidate.challenge.content,activeContents));if(!item){await appendBatch(store,pool,context,false);item=pool.items.find(candidate=>!candidate.usedAt&&isDistinctSecretMission(candidate.challenge.content,activeContents));}if(!item)throw new Error('暂时没有可用的秘密任务，请稍后重试');item.usedAt=new Date().toISOString();await savePool(store,pool);return {challenge:item.challenge,remaining:pool.items.filter(candidate=>!candidate.usedAt).length};});if(result.remaining<=2)void refillMustPool(store,roomId,accountId,context).catch(error=>console.warn('[must-pool]',error instanceof Error?error.message:'refill failed'));return result.challenge;}

export async function refillMustPool(store:Store,roomId:string,accountId:string,context:ChallengeContext){return locked(roomId,async()=>{const pool=await loadPool(store,roomId,accountId);if(!pool||pool.profileFingerprint!==fingerprint(context)||pool.items.filter(item=>!item.usedAt).length>2)return;await appendBatch(store,pool,context,true);});}
