import { TaskPanel, PageFrame, SummaryPanel, DetailDialog, ExpandableImage } from './AdaptivePage';
import { useEffect, useRef, useState } from 'react';
import type { GameHistory, GameOverview, RoomSnapshot, StoryRuling, StoryScoreDetail } from '@ruxiju/shared';
import { api, uid } from './api';
import './story.css';

type View=NonNullable<GameOverview['story']>;
type Own={ownTask?:string;ownVote?:string;ending?:string;manualTasks?:Record<string,string>};
const labels={setup:'准备本场故事',relay:'续写你的这一段',reveal:'故事走向既定结局',voting:'选出最佳段落',review:'一起评议这个故事',complete:'故事已落幕'};
const defaults:StoryRuling={characterPresent:true,ooc:false,disconnected:false,endingConnection:false,spoiler:false,reason:''};
export function StoryRules(){return <><p>AI 自动生成故事开篇与既定结局，同时为每位玩家秘密分配一个任务。玩家按顺序续写剧情，在自己的段落中推进故事并完成任务。每人接龙时下方可录音辅助。全员完成后投票选出最佳段落，贴合人设、任务完成、剧情连贯者加分。</p><SummaryPanel id="story-detail-0" title="完整游戏规则"><ol className="dont-rules must-rules"><li><strong>开局准备</strong><span>本场可选择跨 IP 角色或自定义人设。开篇全员可见，结局在公布前仅主持可见，秘密任务在评议前仅本人可见。主持可调整顺序，开局后首尾、任务与顺序锁定。</span></li><li><strong>依次接龙</strong><span>每人 60 秒，可超时。建议 2–5 句、最多 500 字，自己的角色必须登场，尝试完成任务，不 OOC、不脱离世界观、不剧透结局。提交后自动换人，主持可跳过。录音仅作本人草稿，刷新或离开当前回合后清除，不上传。</span></li><li><strong>公布与投票</strong><span>主持公布既定结局后，每人投一票选别人已提交的段落，不可改票。无候选人无需投票；主持可提前结束，未投票视为弃权。投票结束后公开任务并评议。</span></li><li><strong>得分</strong><span>每票 +2；有票的并列最高者各 +3；除作者外全体玩家认可任务完美完成 +2；巧妙衔接结局 +1；未出现本人角色 −2；严重 OOC −2；剧情断层 −1。主持确认规则裁定，非默认裁定须说明理由。</span></li><li><strong>例外与胜负</strong><span>被跳过仅计 −2，剧透者本轮归零。最高分获胜，最低分接受现场惩罚，并列共享名次，全员同分免罚。本场为单轮，分数计入聚会总分。</span></li></ol></SummaryPanel></>;}

export function StoryGame({room,memberId,onRefresh,onExit,onHost,onRules}:{room:RoomSnapshot;memberId:string;onRefresh:(room:RoomSnapshot)=>void;onExit:()=>void;onHost:()=>void;onRules:()=>void}){
  const game=room.game!,v=game.publicState as unknown as View,own=game.privateState?.story as Own|undefined;
  const host=Boolean(room.members.find(m=>m.accountId===memberId)?.hostRole);
  const me=v.participants?.find(p=>p.accountId===memberId);
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[generating,setGenerating]=useState(false);
  const pending=useRef(false);
  const [name,setName]=useState(me?.playerRole??''),[persona,setPersona]=useState(me?.persona??'');
  const [endingHint,setEndingHint]=useState(v.endingHint??'');
  const [opening,setOpening]=useState(v.opening??''),[ending,setEnding]=useState(own?.ending??''),[tasks,setTasks]=useState<Record<string,string>>(own?.manualTasks??{});
  const [content,setContent]=useState('');
  useEffect(()=>{setNotice('');},[v.stage]);
  useEffect(()=>{setOpening(v.opening??'');setEndingHint(v.endingHint??'');setEnding(own?.ending??'');setTasks(own?.manualTasks??{});},[v.opening,v.endingHint,own?.ending,own?.manualTasks]);
  const act=async(action:string,payload:Record<string,unknown>={})=>{
    if(pending.current)return;pending.current=true;setBusy(true);setNotice('');if(action==='story-generate')setGenerating(true);
    try{const data=await api<{room:RoomSnapshot}>(`/rooms/${room.code}/actions`,{method:'POST',body:JSON.stringify({gameId:'story',actionId:uid(),action,payload:{...payload,sessionId:game.sessionId}})});onRefresh(data.room);if(action==='story-submit-segment')setContent('');setNotice(action==='story-set-character'?'角色已保存，请主持重新生成或补齐故事。':action==='story-set-story'?'首尾与任务已完整保存。':'');}
    catch(error){setNotice(error instanceof Error?error.message:'操作失败，请重试');}finally{pending.current=false;setBusy(false);setGenerating(false);}
  };
  const isTurn=v.stage==='relay'&&v.currentSpeakerId===memberId;
  const advanceLabel=({setup:'开始接龙',relay:'跳过当前玩家',reveal:'公布结局，开始投票',voting:'结束投票，进入评议',review:'确认并结算',complete:''})[v.stage];
  const canSettle=v.segments.every(seg=>v.rulings?.[seg.accountId]);
  const move=(index:number,offset:number)=>{const order=[...v.order];[order[index],order[index+offset]]=[order[index+offset],order[index]];void act('story-reorder',{order});};
  return <PageFrame scope={`${room.game?.sessionId}:${memberId}`} className="play-surface story-game">
    <header className="play-header"><button onClick={onExit} aria-label="返回房间">←</button><strong>故事接龙</strong>{host?<button className="host-chip" onClick={onHost}>主持</button>:<span className="connection"><i/>在线</span>}</header>
    <section className="play-stage"><div className="stage-symbol"><span>✎</span></div><h1>{labels[v.stage]}</h1>
      <div className="page-columns"><TaskPanel className="story-content page-main">
        {v.stage==='setup'?<>
          {me&&<SummaryPanel id="story-detail-1" title={<span>本场角色 · {me.playerRole}</span>} defaultOpen={!v.readyToStart}><div className="story-fields"><label className="field"><span>角色姓名（可跨 IP 或自定义）</span><input maxLength={40} value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>角色人设</span><textarea maxLength={500} value={persona} onChange={e=>setPersona(e.target.value)} placeholder="性格、能力、说话方式…"/></label><p className="muted">仅影响本场。修改角色后，需要重新生成首尾与任务。</p><button disabled={busy||!name.trim()||!persona.trim()||name===me.playerRole&&persona===me.persona} onClick={()=>void act('story-set-character',{playerRole:name,persona})}>保存本场角色</button></div></SummaryPanel>}
          <section><h2>接龙顺序</h2><ol className="story-order">{v.order.map((id,index)=>{const p=v.participants.find(p=>p.accountId===id)!;return <li key={id}><span>{index+1}. {p.displayName} · {p.playerRole}</span>{host&&<div><button aria-label={`上移${p.displayName}`} disabled={busy||index===0} onClick={()=>move(index,-1)}>↑</button><button aria-label={`下移${p.displayName}`} disabled={busy||index===v.order.length-1} onClick={()=>move(index,1)}>↓</button></div>}</li>;})}</ol></section>
          {host?<><button className="primary" disabled={busy} onClick={()=>void act('story-generate')}>{generating?'正在生成首尾与秘密任务…':v.readyToStart?'重新生成故事与任务':'AI 生成故事与任务'}</button><p className="muted">确认大家的人设后生成。生成失败可重试，或在下方手动补齐。</p><SummaryPanel id="story-detail-2" title="手动补齐首尾与任务"><div className="story-fields"><label className="field"><span>故事开篇（全员可见）</span><textarea value={opening} maxLength={1000} onChange={e=>setOpening(e.target.value)}/></label><label className="field"><span>模糊结局提示（全员可见，保留悬念）</span><textarea value={endingHint} maxLength={200} onChange={e=>setEndingHint(e.target.value)}/></label><label className="field"><span>完整结局（公布前仅主持可见）</span><textarea value={ending} maxLength={1000} onChange={e=>setEnding(e.target.value)}/></label>{v.participants.map(p=><label className="field" key={p.accountId}><span>{p.displayName}的秘密任务</span><textarea value={tasks[p.accountId]??''} maxLength={500} onChange={e=>setTasks({...tasks,[p.accountId]:e.target.value})}/></label>)}<button disabled={busy||!opening.trim()||!endingHint.trim()||!ending.trim()||v.participants.some(p=>!tasks[p.accountId]?.trim())} onClick={()=>void act('story-set-story',{opening,endingHint,ending,tasks})}>保存全部首尾与任务</button></div></SummaryPanel></>:<p className="muted">{v.readyToStart?'故事已就绪，等待主持确认顺序并开始。':'等待主持生成或补齐故事，确认顺序后开始。'}</p>}
          {v.readyToStart&&<p role="status">首尾与每人的任务已就绪 · {v.source==='ai'?'AI 生成':v.source==='manual'?'主持手动编排':'历史内容'}</p>}
        </>:null}
        {own?.ownTask&&v.stage!=='review'&&v.stage!=='complete'&&<article className="story-task-chip"><span>你的秘密任务 · 仅自己可见</span><strong>{own.ownTask}</strong></article>}
        
        {host&&own?.ending&&!v.ending&&<SummaryPanel id="story-detail-3" title="主持预览既定结局 · 请勿展示屏幕"><p>{own.ending}</p></SummaryPanel>}
        {v.stage==='relay'&&<><StoryTimer startedAt={v.turnStartedAt}/>{isTurn?<><label className="field"><span>你的段落 · 建议 2–5 句，最多 500 字</span><textarea value={content} maxLength={500} onChange={e=>setContent(e.target.value)} placeholder={`让${me?.playerRole??'你的角色'}登场，推进故事并尝试完成任务…`}/><small>{content.length}/500</small></label><PrivateRecorder key={`${game.sessionId}-${v.currentSpeakerId}`} active={isTurn}/><button className="primary" disabled={busy||!content.trim()} onClick={()=>void act('story-submit-segment',{content})}>提交这一段</button></>:<p className="story-waiting">轮到 {v.currentSpeakerName} · {v.currentSpeakerRole} 续写。</p>}</>}
        {v.stage==='reveal'&&<p>接龙已结束，等待主持公布预设结局，再一起投票。</p>}
        {v.stage==='voting'&&<section><h2>你的一票</h2><p>不能投自己，投出后不可修改。票数将在评议时公布。</p><div className="story-vote-list">{v.segments.filter(seg=>seg.accountId!==memberId).map(seg=><button className={`story-vote-card ${own?.ownVote===seg.accountId?'selected':''}`} key={seg.accountId} disabled={busy||Boolean(own?.ownVote)||!me} onClick={()=>void act('story-vote',{targetAccountId:seg.accountId})}><strong>{seg.displayName} · {seg.playerRole}</strong><p>{seg.content}</p><span>{own?.ownVote===seg.accountId?'已投此段':'投给这一段'}</span></button>)}</div>{!v.segments.some(seg=>seg.accountId!==memberId)&&<p>你没有可投的候选段落，无需投票。</p>}</section>}
        {(v.stage==='review'||v.stage==='complete')&&<><StoryScores view={v}/>{v.stage==='review'&&<p>任务奖励需其他全体参与者明确认可；未回应或有异议均不加分。以下分数在主持结算前仍会更新。</p>}{v.participants.map(p=>{const seg=v.segments.find(seg=>seg.accountId===p.accountId);return <SummaryPanel id={"story-detail-"+(p.accountId)} title={<span>{p.displayName} · {seg?'任务与裁定':'被跳过 −2 分'}</span>} key={p.accountId} defaultOpen={v.stage==='review'}><p>人设：{p.playerRole} · {p.persona}</p><p>秘密任务：{v.tasks?.[p.accountId]||'旧记录未保存'}</p>{seg&&<><p>{seg.content}</p><p>任务认可 {Object.values(v.approvals?.[p.accountId]??{}).filter(Boolean).length}/{v.participants.length-1}</p><ul className="story-approval-list">{v.participants.filter(other=>other.accountId!==p.accountId).map(other=><li key={other.accountId}>{other.displayName}：{v.approvals?.[p.accountId]?.[other.accountId]===true?'认可':v.approvals?.[p.accountId]?.[other.accountId]===false?'有异议':'未回应'}</li>)}</ul>{v.stage==='review'&&me&&p.accountId!==memberId&&<div className="story-buttons"><button aria-pressed={v.approvals?.[p.accountId]?.[memberId]===true} disabled={busy} onClick={()=>void act('story-approve-task',{targetAccountId:p.accountId,approved:true})}>认可任务完美完成</button><button aria-pressed={v.approvals?.[p.accountId]?.[memberId]===false} disabled={busy} onClick={()=>void act('story-approve-task',{targetAccountId:p.accountId,approved:false})}>有异议</button></div>}{v.stage==='review'&&host?<RulingEditor key={`${p.accountId}-${JSON.stringify(v.rulings?.[p.accountId])}`} value={v.rulings?.[p.accountId]} busy={busy} onSave={r=>void act('story-rule',{targetAccountId:p.accountId,...r})}/>:<p>主持裁定：{v.rulings?.[p.accountId]?.reason||(v.rulings?.[p.accountId]?'无额外加扣分':'未记录')}</p>}</>}<ScoreDetail detail={v.details?.[p.accountId]}/></SummaryPanel>;})}</>}
        {notice&&<p role="alert" className="story-notice">{notice}</p>}<button className="rules-link" onClick={onRules}>查看本局规则</button>
      </TaskPanel><aside className="page-support"><StoryText view={v}/></aside></div>
    </section>
    <footer className="play-footer story-footer"><div className="story-footer-progress"><span>{v.submittedCount}/{v.total} 段已续写</span>{v.stage==='voting'&&<span>{v.votedCount}/{v.voterCount} 人已投票</span>}</div>{host&&v.stage!=='complete'&&<button className={v.stage==='relay'?'story-skip':'primary'} disabled={busy||v.stage==='setup'&&!v.readyToStart||v.stage==='review'&&!canSettle} onClick={()=>void act('story-next',{expectedStage:v.stage,expectedSpeakerId:v.currentSpeakerId})}>{advanceLabel}</button>}{host&&v.stage==='review'&&!canSettle&&<small>请逐人保存裁定后结算。</small>}{v.stage==='complete'&&<button className="primary" onClick={onExit}>返回聚会经历</button>}</footer>
  </PageFrame>;
}

function StoryTimer({startedAt}:{startedAt:number|null}){const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);const left=Math.ceil((60000-(now-(startedAt??now)))/1000);return <p className="story-timer" role="timer">{left>=0?`思考时间 ${left} 秒`:`已超时 ${-left} 秒，仍可继续写作`}</p>;}

function PrivateRecorder({active}:{active:boolean}){
  const [recording,setRecording]=useState(false),[requesting,setRequesting]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState('');
  const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),alive=useRef(true),objectUrl=useRef(''),acquiring=useRef(false);
  useEffect(()=>{alive.current=active;return()=>{alive.current=false;if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);};},[active]);
  const discard=()=>{if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);objectUrl.current='';setUrl('');};
  const toggle=async()=>{
    if(recorder.current?.state==='recording'){recorder.current.stop();return;}
    if(acquiring.current)return;
    setError('');if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('当前浏览器无法录音，请使用支持录音的浏览器，并通过 HTTPS 或本机地址访问。');return;}
    acquiring.current=true;setRequesting(true);
    try{
      const audio=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current){audio.getTracks().forEach(t=>t.stop());return;}stream.current=audio;
      const mime=['audio/webm;codecs=opus','audio/mp4','audio/webm','audio/ogg;codecs=opus'].find(type=>MediaRecorder.isTypeSupported(type));
      const instance=new MediaRecorder(audio,mime?{mimeType:mime}:undefined);recorder.current=instance;const chunks:BlobPart[]=[];
      instance.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
      instance.onstop=()=>{audio.getTracks().forEach(t=>t.stop());if(!alive.current)return;setRecording(false);discard();if(chunks.length){objectUrl.current=URL.createObjectURL(new Blob(chunks,{type:instance.mimeType}));setUrl(objectUrl.current);}};
      instance.onerror=()=>{audio.getTracks().forEach(t=>t.stop());if(alive.current){setRecording(false);setError('录音中断，请重新录制。');}};
      discard();instance.start();setRecording(true);
    }catch(err){stream.current?.getTracks().forEach(t=>t.stop());if(alive.current)setError(err instanceof DOMException&&err.name==='NotAllowedError'?'麦克风权限被拒绝，请在浏览器设置中允许后重试。':'未能打开麦克风，请检查设备是否连接或被其他应用占用。');}
    finally{acquiring.current=false;if(alive.current)setRequesting(false);}
  };
  return <div className="story-recorder"><div className="story-buttons"><button disabled={requesting} aria-pressed={recording} onClick={()=>void toggle()}>{requesting?'等待麦克风授权…':recording?'停止录音':url?'重新录制':'录音留存灵感'}</button>{url&&!recording&&<button onClick={discard}>删除录音</button>}</div>{url&&!recording&&<audio controls src={url}/>}<small>录音仅自己可见，不上传；刷新或离开当前回合后清除。</small>{error&&<p role="alert">{error}</p>}</div>;
}

function RulingEditor({value,busy,onSave}:{value:StoryRuling|undefined;busy:boolean;onSave:(r:StoryRuling)=>void}){
  const [r,setR]=useState<StoryRuling>(value??defaults);const nondefault=!r.characterPresent||r.ooc||r.disconnected||r.endingConnection||r.spoiler;
  return <fieldset className="story-ruling"><legend>主持规则裁定</legend>{([['characterPresent','自己的角色已登场'],['ooc','严重 OOC（−2）'],['disconnected','剧情断层（−1）'],['endingConnection','巧妙衔接结局（+1）'],['spoiler','强行剧透（本轮归零）']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={r[key]} onChange={e=>setR({...r,[key]:e.target.checked})}/><span>{label}{key==='characterPresent'?'，未登场 −2':''}</span></label>)}<label className="field"><span>裁定理由{nondefault?'（必填）':'（可选）'}</span><textarea maxLength={500} value={r.reason} onChange={e=>setR({...r,reason:e.target.value})}/></label><button disabled={busy||nondefault&&!r.reason.trim()} onClick={()=>onSave(r)}>{value?'保存裁定修改':'确认并保存裁定'}</button></fieldset>;
}
export function ScoreDetail({detail}:{detail:StoryScoreDetail|undefined}){if(!detail)return <p className="muted">旧记录未保存计分依据。</p>;if(detail.skipped)return <p>被跳过 −2 · 本轮 −2 分</p>;if(detail.spoiler)return <p>剧透裁定覆盖其他加扣分 · 本轮 0 分</p>;const entries=[['选票',detail.votes],['最佳段落',detail.best],['任务',detail.task],['衔接结局',detail.connection],['角色未登场',detail.missingCharacter],['OOC',detail.ooc],['剧情断层',detail.disconnected]] as const;return <p className="story-score-detail">{entries.filter(([,n])=>n!==0).map(([label,n])=>`${label} ${n>0?'+':''}${n}`).join(' · ')||'无加扣分'} · 合计 {detail.total} 分</p>;}
export function StoryText({view}:{view:Pick<View,'opening'|'endingHint'|'ending'|'segments'>}){return <>{view.opening&&<SummaryPanel id="opening" title="故事开篇"><p>{view.opening}</p></SummaryPanel>}{view.endingHint&&!view.ending&&<SummaryPanel id="ending-hint" title="模糊结局提示" defaultOpen><p>{view.endingHint}</p><small>完整结局将在接龙结束后公布。</small></SummaryPanel>}{view.segments.length>0&&<SummaryPanel id="story-segments" title="此前段落" status={view.segments.length+' 段'}><ol className="story-thread-list">{view.segments.map((seg,index)=><li key={seg.accountId+'-'+index}><div><strong>{seg.displayName}</strong><small>{seg.playerRole}</small></div><p>{seg.content}</p></li>)}</ol></SummaryPanel>}{view.ending&&<SummaryPanel id="ending" title="既定结局" defaultOpen><p>{view.ending}</p></SummaryPanel>}</>;}
function StoryScores({view}:{view:View}){const sorted=[...view.participants].sort((a,b)=>(view.points[b.accountId]??0)-(view.points[a.accountId]??0));const best=view.points[sorted[0]?.accountId]??0,worst=view.points[sorted.at(-1)?.accountId??'']??0;return <section><h2>{view.stage==='complete'?'本轮得分':'当前计分'}</h2><ol className="story-ranking">{sorted.map(p=><li key={p.accountId}><span>{p.displayName} · {p.playerRole}{view.stage==='complete'&&view.points[p.accountId]===best?' · 获胜':''}{view.stage==='complete'&&best!==worst&&view.points[p.accountId]===worst?' · 接受现场惩罚':''}</span><strong>{view.points[p.accountId]??0} 分</strong></li>)}</ol>{view.stage==='complete'&&best===worst&&<p>全员同分，本轮免罚。</p>}</section>;}
export function StoryOverview({view}:{view:View}){return <div className="story-content"><p>{labels[view.stage]} · {view.submittedCount}/{view.total} 段{view.stage==='relay'?` · ${view.currentSpeakerName}接龙中`:''}{view.stage==='voting'?` · ${view.votedCount}/${view.voterCount} 人已投票`:''}</p>{view.ownTask&&<p>你的秘密任务：{view.ownTask}</p>}<StoryText view={view}/>{(view.stage==='review'||view.stage==='complete')&&<StoryScores view={view}/>}</div>;}
export function StoryHistory({history}:{history:NonNullable<GameHistory['story']>}){return <div className="story-content"><StoryText view={history}/><h3>完整复盘</h3>{history.results.map(p=><SummaryPanel id={"story-detail-"+(p.accountId)} title={<span>{p.displayName} · {p.points} 分{p.winner?' · 获胜':''}{p.loser?' · 接受现场惩罚':''}</span>} key={p.accountId}><p>{p.playerRole} · {history.participants?.find(a=>a.accountId===p.accountId)?.persona??'人设未记录'}</p><p>任务：{history.tasks?.[p.accountId]??history.segments.find(s=>s.accountId===p.accountId)?.task??'未记录'}</p><p>{history.segments.find(s=>s.accountId===p.accountId)?.content??'未提交段落，被跳过'}</p><p>主持裁定：{history.rulings?.[p.accountId]?.reason||(history.rulings?.[p.accountId]?'无额外加扣分':'未记录')}</p><ScoreDetail detail={history.details?.[p.accountId]}/><p>任务认可：{history.approvals?history.results.filter(other=>other.accountId!==p.accountId).map(other=>`${other.displayName}：${history.approvals?.[p.accountId]?.[other.accountId]===true?'认可':history.approvals?.[p.accountId]?.[other.accountId]===false?'有异议':'未回应'}`).join('；'):'未记录'}</p></SummaryPanel>)}<h3>投票记录</h3><ul>{history.results.map(p=>{const vote=history.votes.find(v=>v.voterAccountId===p.accountId);return <li key={p.accountId}>{p.displayName} → {vote?.targetName??(history.segments.some(seg=>seg.accountId!==p.accountId)?'弃权':'无可投候选人')}</li>;})}</ul>{history.results.length>0&&history.results.every(p=>p.points===history.results[0].points)&&<p>全员同分，本轮免罚。</p>}</div>;}
